### ISSUE TITLE
Yukari Lib Crash with  Reinforced tools

### ISSUE THREAD

**Issue by DatrixTHLK** [C6H2Cl2/YukariLib#1]
Minecraft Forge: 1.10.2: 12.18.3.2185
YukariLib: 1.0.1
Reinforced Tools: 2.0.0
https://gist.github.com/DatrixTHLK/831ad2509db982d227834e710a150c87

I will downgrade (1.5.0) til fix is issued

**Comment by C6H2Cl2** [comment]
I know it, but I have no idea why it causes (;_;)

**Comment by C6H2Cl2** [comment]
It was fixed on YukariLib 1.0.2.
But I don't know why it was fixed (´◦ω◦｀)
I think it was mistakes in compile.
Thank you for reporting!

**Comment by DatrixTHLK** [comment]
Thanks for responding and the fix. :)
