### ISSUE TITLE
Crash when updating to yukariLib-1.7.10-1.2.2

### ISSUE THREAD

**Issue by BattleExplosion** [C6H2Cl2/YukariLib#14]
[crash-2017-04-01_03.21.43-client.txt](https://github.com/C6H2Cl2/YukariLib/files/887542/crash-2017-04-01_03.21.43-client.txt)

When i log into my server it crashes.

**Comment by C6H2Cl2** [comment]
I knew it and fixed, but I forgot release.
Sorry(-.-;)
Please use 1.7.10-1.2.3

**Comment by BattleExplosion** [comment]
Thanks very much ^_^
