### ISSUE TITLE
Breaks any offline environment

### ISSUE THREAD

**Issue by ghost** [C6H2Cl2/YukariLib#17]
This lib can't be used without internet, do not bother telling me to play Minecraft WITH internet because I live in CUBA so internet in a computer isn't an option... Seriously, even if someone had a computer with internet in here the speed would be limited to less that 2mbps witch is useless for almost everything...
Why so slow you may ask? Internet here by ETECSA is distributed to houses by ADSL and the cost is 15$ for the slowest setup (256kbps) and 15$ more for 30 hours of internet. The hours must be bought each month if you which to follow that offer...otherwise it's 2$ for 2 hours by cards...
Even if someone actually owned Minecraft in Cuba he could not play it and be an authenticated user because it's simply impossible...
Anyways Minecraft itself doesn't take the authentication seriously because even a simply command line is enought to launch Minecraft without demo mode enabled so why bother to make an "anti crack" system? Minecraft doesn't even need to be cracked to play offline!

**Comment by JUser99** [comment]
Anyway it doesn't matter because I don't even use this lib and it aeems it wqa abandoned since the last update was two years ago...

**Comment by ghost** [comment]
Meh, this seems abandoned... Two years ago was the last update anyway...
